language: node_js
node_js:
 — “8.9.4”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
filter_secrets:
  --false
after_success:
 — firebase deploy — project projectId — token $FIREBASE_TOKEN