language: node_js
node_js:
 — “8.9.4.0”
script:
 — echo “Deploy!!”
install:
 — npm install -g firebase-tools
filter_secrets:
  --false
after_success:
 — firebase deploy — project "athletic-24d64" — token $FIREBASE_TOKEN